name: social_embed_webview
description: Provide a widget to easily embed social media post in flutter using web embed feature by the platform.
version: 0.3.2
homepage: https://github.com/aker99/social_embed_webview

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.2"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.8.0
  url_launcher: ^6.3.0
  localstorage: ^5.0.0
  http: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

