name: social_embed_webview
description: Provide a widget to easily embed social media post in flutter using web embed feature by the platform.
version: 0.3.3
homepage: https://github.com/aker99/social_embed_webview

environment:
  sdk: '>=3.7.2 <4.0.0'
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.9.0
  url_launcher: ^6.3.0
  localstorage: ^5.0.0
  http: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

